title: Patterns in the Pandemic, 2021 - <Your Name>                 # *** Enter your name here
subtitle: 'An INSPIRE 1A03 Module'

remote_theme: pmarsceill/just-the-docs                              # don't edit this. 
# color_scheme: dark                                                # Uncomment this if you would like to use dark mode. 


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.    
heading_anchors: true                                               # don't edit this.


# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true                                                   # don't edit this.
back_to_top_text: "Back to top"                                     # don't edit this.

# Footer last edited timestamp
last_edit_timestamp: true # don't edit -- show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"                       # don't edit this. Time format

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link               # don't edit this.
gh_edit_link_text: "View this content on GitHub"                    # don't edit this.
gh_edit_repository: "https://github.com/inspire-1a03/pip-2021-results" #*** ENTER the URL for your github repo
gh_edit_branch: "main" # the branch that your docs is served from   # don't edit this.
gh_edit_view_mode: "tree" # don't edit this. "tree" or "edit" if you want the user to jump into the editor immediately


plugins:                                                            # don't edit this.
  - jekyll-remote-theme
  - jekyll-seo-tag

# You can delete the following lines if you don't want to share your work openly
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_name: "Creative Commons Attribution 4.0 International License"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"
